packages:
  - 'packages/*' # all packages in direct subdirs of packages/
  - 'components/**' # all packages in subdirs of components/
  - '!**/test/**' # exclude packages that are inside test directories