packages:
  - 'packages/*' # all packages in direct subdirs of packages/
  - 'private/*' # all packages in direct subdirs of private/
  - '!**/test/**' # exclude packages that are inside test directories